# Generated by Django 4.2.3 on 2023-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
